### ISSUE TITLE
mqtt subsciptions seems to get lost

### ISSUE THREAD

**Issue by tbowmo** [tbowmo/chromecastcontrol#16]
After some time, it seems that subscriptions to mqtt topics are lost, this leads to unresponsiveness when sending control commands via mqtt to the chromecasts. I haven't been able to locate the issue yet though.

@Stanback @fallberg, you two are the only ones that I know of, that uses this program semi actively, so could you give some feedback, if you guys see the same issue?

**Comment by fallberg** [comment]
I will keep my eyes open. I have noticed some connectivity problems but I am currently refactoring and transitioning my node-red rig from rPi to docker on my NAS so it will take some time for me to provide useful feedback.

**Comment by Stanback** [comment]
@tbowmo I haven't noticed anything specifically but will keep an eye out for this.
