### ISSUE TITLE
volume is not always reported correctly

### ISSUE THREAD

**Issue by tbowmo** [tbowmo/chromecastcontrol#6]
as mentioned in #4 there is sometimes an issue with volume reported from chromecasts

This issue is for tracking / discussing this

**Comment by tbowmo** [comment]
@stanback
When I use tidal, it seems like volume is reported two different places, both in new_cast_status, and in new_media_status. the one in new_media_status is always reported as 1 (100), while the other is changed according to what I set it to in the app.

Could you try the mqttStabilizing branch? It reports the two different volume levels on separate mqtt topics, (volume and volume1) volume is the one received by new_media_status callback, and volume1 is the one received in new_cast_status callback

**Comment by tbowmo** [comment]
Using youtube (with the above mentioned hack), both volume levels get updated simultaneously.
Netflix, only updates volume1
HBO Nordic, only updates volume1

So perhaps volume reporting should be based on the one reported in new_cast_status(), as it seems to be used by all apps.

**Comment by Stanback** [comment]
@tbowmo Thanks for looking into this. 😄 I tried the mqttStabilizing branch and can confirm that cast status is a better place to read the volume from versus getting it from media status. (I also didn't find any cases where media status was better.)

**Comment by tbowmo** [comment]
Thanks for verifying it. I'll split the mqtt branch, and push a fix for the volume settings then.. Perhaps tonight, or tomorrow evening (CET time).
